services:
  - type: web
    name: tienditadulcecitapostgresql
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://tiendita_dwtr_user:KLR24nxWbtBBd2GU5YDFKLvy7DXA1hcJ@dpg-d77k03k50q8c73cs9u10-a/tiendita_dwtr
      - key: JWT_SECRET
        value: tiendita_secret_2025_!xK9mQ
      - key: NODE_ENV
        value: production
